[package]
name = "allua"
version = "0.1.0"
edition = "2021"

[dependencies]
ustr = "1.0"
unicode-ident = "1.0"
unicode-normalization = "0.1"
unicode-properties = "0.1.1"

[dev-dependencies]
expect-test = "1.5.0"
